### ISSUE TITLE
Another concern is when can we achieve support for Arduino's WiFiManager library and Bluetooth related libraries?

### ISSUE THREAD

**Issue by Chenjiek** [board707/w80x_arduino#40]
Another concern is when can we achieve support for Arduino's WiFiManager library and Bluetooth related libraries?
Yesterday, I shared information and screen display of Arduino's W80X on GITHUB in several relevant QQ groups. Many friends asked me when WIFI is supported?

**Comment by AnatolSher** [comment]
Hello! This is a good question and we are working on it currently. This project is called w80x-arduino-iot. But we are not ready to publish it yet. There are still many features to be implemented. Follow our github :)

**Comment by Chenjiek** [comment]
Okay, I look forward to using w801 using WIFI. Thank you for your efforts!

**Comment by divadiow** [comment]
I look forward to wifi support!

I read somewhere that W806 actually has the same core as W801 and wifi can be enable if using the W806 SDK with some modifications. 

http://ask.winnermicro.com/article/186.html

is this true?

**Comment by AnatolSher** [comment]
This discussion does not talk about a proven way to enable the RF module. The author gives a recipe  how to use WM80X-SDK for W806 chips. This is due to a change in the chip's memory map. Our compatriot nvv13 made a special SDK build for this purpose. In theory, all W80X chips are made from one lithographic mask. When monitoring parameters, restrictions are made on operating modes. We have not done any experiments on RF activation on W806/Air103/Air101 chips. Because it doesn't make sense.
https://github.com/nvv13/test/tree/main/test-mk/w806/W806_SDK-linux

In addition:
Check this area. There is a factory calibration of the RF module
![image](https://github.com/board707/w80x_arduino/assets/121094544/03a3c10b-73c1-42bc-a7f3-476eb61e4714)

**Comment by AnatolSher** [comment]
@Chenjiek Hello
You can close this issue because the WiFi plugin is ready and can be downloaded from https://github.com/board707/w80x_arduino_iot.
You can learn how to use it here http://ask.winnermicro.com/article/212.html

**Comment by Chenjiek** [comment]
Received, I will learn how to use it as soon as possible, thank you

**Comment by Chenjiek** [comment]
![屏幕截图 2024-12-24 170505](https://github.com/user-attachments/assets/617feb27-6255-4ed5-9a82-b1046167f33f)
![屏幕截图 2024-12-24 170505](https://github.com/user-attachments/assets/1f861e31-df41-4a9f-9320-29bcda061f09)
Is my path correct? Why don't I seem to know what the effect is and how to use it?

**Comment by divadiow** [comment]
So is WiFi on W806 possible or not?

**Comment by Chenjiek** [comment]
How come w806 has wifi?

**Comment by divadiow** [comment]
I am trying to find out if it even does

**Comment by AnatolSher** [comment]
@Chenjiek Path not correct. Put it to home directory "C:\Users\User\Documents\Arduino\hardware" like this
![image](https://github.com/user-attachments/assets/04433f74-3590-45ef-80ee-fb1e7c373c18)
WiFi have only w800,w801,w802,w803
Result on screen
![image](https://github.com/user-attachments/assets/273a1333-0504-49be-b689-d3c0c2246683)

**Comment by AnatolSher** [comment]
@divadiow We've discussed this topic before. There is probably an RF module in there, because the lithographic mask is probably one for all w80x chips. And even if it is, you won't make it work. Because there is no factory calibration data. And even if you find that data, you can't write it to RO memory. I could go on with that logic :) ...  You also have to take care of the antenna and its impedance... And why is that necessary? It is easier to buy HLK-W801-KIT dev board and not waste your time uselessly

**Comment by divadiow** [comment]
Sure. I have officially given up on W806 with WiFi :)

**Comment by Chenjiek** [comment]
![屏幕截图 2024-12-25 111959](https://github.com/user-attachments/assets/a5ec4f6a-a36b-4005-bfdf-7d635119665c)
Thank you, my friend, I don’t seem to have found the same folder as you. There is no hardware folder in my folder. Do I need to create one myself?

**Comment by AnatolSher** [comment]
@Chenjiek Yes

**Comment by Chenjiek** [comment]
OK, I created the new folder and it's ready to use, thank you! Wish you a happy new year!
